export const LIKE_REQUEST= 'LIKE_REQUEST'
export const LIKE_SUCCESS= 'LIKE_SUCCESS'
export const LIKE_FAIL= 'LIKE_FAIL';
export const CLEAR_MESSAGE= 'CLEAR_MESSAGE';

export const ADD_COMMENT_REQUEST ="ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS ="ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL ="ADD_COMMENT_FAIL"

export const DELETE_COMMENT_REQUEST ="DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS ="DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL ="DELETE_COMMENT_FAIL"


export const CAPTION_UPDATE_REQUEST= "CAPTION_UPDATE_REQUEST"
export const CAPTION_UPDATE_SUCCESS= "CAPTION_UPDATE_SUCCESS";
export const CAPTION_UPDATE_FAIL= "CAPTION_UPDATE_FAIL";

export const  MY_POSTS_REQUEST= 'MY_POSTS_REQUEST';
export const  MY_POSTS_SUCCESS= 'MY_POSTS_SUCCESS';
export const  MY_POSTS_FAIL= 'MY_POSTS_FAIL';

export const NEW_POST_REQUEST= 'NEW_POST_REQUEST';
export const NEW_POST_SUCCESS= 'NEW_POST_SUCCESS';
export const NEW_POST_FAIL= 'NEW_POST_FAIL';

export const USER_POST_REQUEST= "USER_POST_REQUEST"
export const USER_POST_SUCCESS= "USER_POST_SUCCESS"
export const USER_POST_FAIL= "USER_POST_FAIL"

export const DELETE_POST_REQUEST= 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS= 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL= 'DELETE_POST_FAIL';

export const CLEAR_ERRORS= 'CLEAR_ERRORS'